### ISSUE TITLE
Completed Module 03 assignments

### ISSUE THREAD

**Issue by Dominiclemus** [ds4owd-001/md-03-assignments-Dominiclemus#1]
@larnsce 
@mianzg 
@sskorik01 
I do not understand how me as an undergraduate student will go about the second part of the assignment that requires us to go to the field to collect samples. I personally do not have access to such a lab. So please help me out. 
But i have tried searching online and i got related values so i do not know if they can work

**Comment by sskorik01** [comment]
Hi Dominic,

Congratulations for working through the assignments of module 3. I'm not sure what you mean by going to the field to collect values, I don't see anywhere in the exercise where such a think has been asked. Could you elaborate?

**Comment by sskorik01** [comment]
Hi, sorry for the misunderstanding, the assignment 2 is giving you the data and you're supposed to fill an excel sheet with i. You don't have to collect anything in the field

**Comment by Dominiclemus** [comment]
Okay thank you
